version: '3.8'

services:
  alz-interface-demo:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alz-demo.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.alz-demo.tls.certresolver=letsencrypt"
