version: '3.8'

services:
  alz-interface-demo:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alzdetect.rule=Host(`alzdetect.skumyol.com`)"
      - "traefik.http.routers.alzdetect.tls.certresolver=letsencrypt"
